language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install sass
- npm install -g grunt-cli
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: iibMQXHWzaLv5d3AsOm8dHdmUxfBJk1PDOOddNPfOOi2gw4lQaAbdZWu+b7c8WPBGSxFNUu5jTsl++a54Dsl/YtNdFjiVgPEJehAJRUNdGTN8NoaKUlujfpSk5ACO1bcZBi26gqUSWmRwgDrvjDgbOvpIFWPAiowK4+Ig8jtCWA=
  app: imify
  on:
    branch: master
    repo: apergy/imify
